name: "Publish test logs"
description: "Upload test logs to a unique archive name"

inputs:
  archive-type:
    description: "File type for archive name stub (e.g. unit-tests)"
    required: true
  python-version:
    description: "Python version for the archive name stub (e.g. 3.8)"
    required: true
  os:
    description: "OS for the archive name stub (e.g. ubuntu-latest)"
    required: true

outputs:
  archive-name:
    description: "Name of the archive containing the test artifacts"
    value: ${{ steps.archive.outputs.archive-name }}

runs:
  using: composite
  steps:
    - name: "Create unique archive name"
      id: archive
      shell: bash
      run: |
        timestamp=$(date +'%Y-%m-%dT%H-%M-%S')
        archive_name="${{ inputs.archive-type }}_python-${{ inputs.python-version }}_${{ inputs.os }}_$timestamp"
        echo "archive-name=$archive_name" >> $GITHUB_OUTPUT

    - name: "Upload test logs"
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.archive.outputs.archive-name }}
        path: ./logs

    - name: "[INFO] Uploaded test logs"
      shell: bash
      run: |
        title="Uploaded test logs"
        message="Uploaded `./logs` to ${{ steps.archive.outputs.archive-name }}"
        echo "::notice title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
