name: "Publish to PyPI"
description: "Publish artifacts from an archive to PyPI"

inputs:
  archive-name:
    description: "Name of the archive containing the artifacts, leave blank if local"
    default: ""
  repository-url:
    description: "The url for the PyPI index"
    required: true
  working-dir:
    description: "Where to run commands from, primarily supports namespace packaging"
    default: "./"

runs:
  using: composite
  steps:

    - name: "Download artifacts"
      if: ${{ !(inputs.archive-name == "" }}
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.archive-name }}
        path: dist/

    - name: "[INFO] Downloaded artifacts"
      if: ${{ !(inputs.archive-name == "" }}
      shell: bash
      run: |
        title="Downloaded artifacts"
        message="Downloaded artifacts from ${{ inputs.archive-name }}"
        echo "::notice title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"

    - name: "[DEBUG] Found artifacts"
      shell: bash
      working-directory: ${{ inputs.working-dir }}
      run: echo $(ls ./dist)

    - name: "Publish artifacts to PyPI"
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: ${{ inputs.repository-url }}
        packages-dir: ${{ inputs.working-dir }}dist/

    - name: "[INFO] Published artifacts to PyPI"
      shell: bash
      working-directory: ${{ inputs.working-dir }}
      run: |
        title="Published artifacts to PyPI"
        message=$(ls ./dist)
        echo "::notice title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
