name: "Commit changes"
description: "Commit changes and push back up to the remote"

inputs:
  message:
    description: "The commit message"
    required: true
  user:
    description: "The user for the commit"
    default: "Github Build Bot"
  email:
    description: "The email for the commit"
    default: "buildbot@fishtownanalytics.com"

runs:
  using: composite
  steps:
    - name: "[DEBUG] Inputs"
      shell: bash
      run: |
        echo message : ${{ inputs.message }}
        echo user    : ${{ inputs.user }}
        echo email   : ${{ inputs.email }}

    - name: "Commit and push changes"
      shell: bash
      run: |
        git config user.name "${{ inputs.user }}"
        git config user.email "${{ inputs.email }}"
        git pull
        git add .
        git commit -m "[automated] ${{ inputs.message }}"
        git push

    - name: "[INFO] Committed and pushed changes"
      shell: bash
      run: |
        title="Committed and pushed changes"
        message="Committed and pushed changes back up to remote"
        echo "::notice title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
