name: "Audit GitHub tag"
description: "Get metadata about a release tag"

inputs:
  tag:
    description: "The tag to audit (e.g. v1.0.0b1)"
    required: true
  repo-url:
    description: "The URL to the repo (e.g. https://github.com/dbt-labs/dbt-adapters)"
    required: true

outputs:
  exists:
    description: "Indicates if the tag exists"
    value: ${{ steps.tag.outputs.exists }}
  sha:
    description: "The commit associated with the tag if the tag exists"
    value: ${{ steps.commit.outputs.sha }}
  is-draft:
    description: "If the tag exists, indicates if it is a draft"
    value: ${{ steps.draft.outputs.is-draft }}

runs:
  using: composite
  steps:
    - name: "Check if `${{ inputs.tag }}` exists in `${{ inputs.repo-url }}`"
      id: tag
      shell: bash
      run: |
        output=$((gh release view ${{ inputs.tag }} --json isDraft,targetCommitish --repo ${{ inputs.repo-url }}) 2>&1) || true
        echo "results=$output" >> $GITHUB_OUTPUT
        if [[ "$output" == "release not found" ]]
        then
          echo "exists=false" >> $GITHUB_OUTPUT
        else
          echo "exists=true" >> $GITHUB_OUTPUT
        fi
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: "Get the commit associated with `${{ inputs.tag }}`"
      id: commit
      if: ${{ fromJSON(steps.tag.outputs.exists) == true }}
      shell: bash
      run: |
        sha=$(jq -r '.targetCommitish' <<< "$output")
        echo "sha=$sha" >> $GITHUB_OUTPUT

    - name: "Check if `${{ inputs.tag }}` is a draft release"
      id: draft
      if: ${{ fromJSON(steps.tag.outputs.exists) == true }}
      shell: bash
      run: |
        is-draft=$(jq -r '.isDraft' <<< "${{ steps.tag.outputs.results }}")
        if [[ $is-draft == true ]]
        then
          echo "is-draft=true" >> $GITHUB_OUTPUT
        else
          echo "is-draft=false" >> $GITHUB_OUTPUT
        fi

    - name: "[DEBUG] Tag metadata"
      shell: bash
      run: |
        echo tag       : ${{ inputs.tag }}
        echo repo-url  : ${{ inputs.repo-url }}
        echo exists:   : ${{ steps.release.outputs.exists }}
        echo sha       : ${{ steps.commit.outputs.sha }}
        echo is-draft  : ${{ steps.draft.outputs.is-draft }}
