name: "Publish GitHub draft release as full release"
description: "Publish an existing draft release as a non-draft release"

inputs:
  tag:
    description: "The tag to publish (i.e. v1.0.0b1)"
    required: true
  repo-url:
    description: "The URL to the repo (https://github.com/dbt-labs/dbt-adapters"
    required: true

runs:
  using: composite
  steps:
    - name: "Publish `${{ inputs.tag }}` as full release"
      shell: bash
      run: gh release edit ${{ inputs.tag }} --draft=false --repo ${{ inputs.repo-url }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: "[INFO] Published draft as full release"
      shell: bash
      run: |
        title="Released draft as non-draft release on GitHub"
        message="tag: ${{ inputs.tag }} repo: ${{ inputs.repo-url }}"
        echo "::notice title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
