name: "Build"
run-name: "Build ${{ inputs.package }}==${{ inputs.version}} for deployment to ${{ deploy-to }}"

on:
  push:
    branches:
      - "main"
  merge_group:
    types: [checks_requested]
  workflow_dispatch:
    inputs:
      package:
        description: "Choose what to publish"
        type: choice
        options:
          - dbt-adapters
          - dbt-tests-adapter
      version:
        description: "The release version number (i.e. 1.0.0b1)"
        type: string
        required: true
      deploy-to:
        description: "Choose where to publish"
        type: choice
        options:
          - prod
          - test
  workflow_call:
    inputs:
      package:
        description: "Choose what to publish (dbt-adapters, dbt-tests-adapter)"
        type: string
      version:
        description: "The release version number (i.e. 1.0.0b1)"
        type: string
        required: true
      deploy-to:
        description: "Choose where to publish"
        type: string
        default: prod
    outputs:
      archive-name: ${{ jobs.build.outputs.archive-name }}

permissions: read-all

# will cancel previous workflows triggered by the same event and for the same ref for PRs or same SHA otherwise
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ inputs.package }}-${{ inputs.version }}-${{ inputs.deploy-to }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  NOTIFICATION_PREFIX: "[Build]"

jobs:
  build:
    name: "Build, test and publish to PyPi"
    runs-on: ubuntu-latest
    outputs:
      archive-name: ${{ steps.archive.outputs.archive-name }}

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: "Setup `hatch`"
        uses: ./.github/actions/setup-hatch

      - name: "Archive name"
        id: archive
        uses: ./.github/actions/build-archive-name

      - name: "Build `dbt-adapters`"
        if: ${{ inputs.package == 'dbt-adapters' }}
        uses: ./.github/actions/build
        with:
          archive-name: ${{ steps.archive.outputs.archive-name }}

      - name: "Build `dbt-tests-adapter`"
        if: ${{ inputs.package == 'dbt-tests-adapter' }}
        uses: ./.github/actions/build
        with:
          archive-name: ${{ steps.archive.outputs.archive-name }}
          working-dir: "./dbt-tests-adapter/"
