name: "Build artifacts"
run-name: "Build `${{ inputs.package }}==${{ inputs.version}}` from `${{ inputs.branch }}` for deployment to `${{ deploy-environment }}`"

on:
    workflow_call:
        inputs:
            package:
                description: "The package being built"
                type: string
            branch:
                description: "The branch to use to build the artifacts"
                type: string
                default: "main"
        outputs:
            archive-name:
                value: ${{ jobs.build-artifacts.outputs.archive-name }}
                description: "The name used for the upload archive"
                type: string
            working-directory:
                value: ${{ jobs.build-artifacts.outputs.working-directory }}
                description: "The working directory for the package"
                type: string

permissions: read-all

# don't try to build the same version of the same package, the archive name could collide
concurrency:
    group: "${{ github.workflow }}-${{ inputs.package }}-${{ inputs.version }}-${{ inputs.deploy-environment }}"
    cancel-in-progress: true

env:
    NOTIFICATION_PREFIX: "Build artifacts"

jobs:
    build-artifacts:
        name: "Build artifacts"
        runs-on: ubuntu-latest
        outputs:
            archive-name: ${{ steps.archive.outputs.name }}
            working-directory: ${{ steps.working-directory.outputs.path }}
        steps:
        -   name: "Set: archive-name"
            id: archive
            shell: bash
            run: |
                name=${{ inputs.package }}-${{ inputs.version }}-${{ inputs.deploy-environment }}
                echo "name=$name" >> $GITHUB_OUTPUT

        -   name: "Set: working-directory"
            id: working-directory
            shell: bash
            run: |
                if [[ ${{ inputs.package }} == "dbt-tests-adapter" ]]; then
                  path="./dbt-tests-adapter/"
                else
                  path="./"
                fi
                echo "path=$path" >> $GITHUB_OUTPUT

        -   name: "Build artifacts"
            uses: dbt-labs/actions/hatch/artifacts/create.yml@add-hatch-actions
            with:
                archive-name: ${{ steps.archive.outputs.name }}
                working-directory: ${{ needs.working-directory.outputs.path }}
