name: "Code quality"

on:
  pull_request:
    branches:
      - "main"
      - "*.latest"
  workflow_call:
    inputs:
      branch:
        description: "The branch to run code quality on"
        type: string
        default: "main"
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to run code quality on"
        type: string
        default: "main"

permissions: read-all

defaults:
  run:
    shell: bash

# cancel the previous code quality run if a new one starts with the same parameters
concurrency:
  group: ${{ github.workflow }}-${{ contains(github.event_name, 'workflow') && inputs.branch || contains(github.event_name, 'pull_request') && github.event.pull_request.head.ref }}
  cancel-in-progress: true

env:
  NOTIFICATION_PREFIX: "[Code quality]"

jobs:
  code-quality:
    name: "Code quality"
    runs-on: ubuntu-latest
    steps:
      - name: "[DEBUG] Inputs"
        run: |
          echo branch              : ${{ inputs.branch }}
          echo lint-command        : ${{ inputs.lint-command }}
          echo typecheck-command   : ${{ inputs.typecheck-command }}
          echo NOTIFICATION_PREFIX : ${{ env.NOTIFICATION_PREFIX }}

      - name: "Check out `${{ inputs.branch }}`"
        uses: actions/checkout@v4
        with:
          ref: ${{ contains(github.event_name, 'workflow') && inputs.branch || contains(github.event_name, 'pull_request') && github.event.pull_request.head.ref }}
          persist-credentials: false

      - name: "Setup `hatch`"
        uses: ./.github/actions/setup-hatch

      - name: "Run linters"
        run: hatch run lint:all

      - name: "Run typechecks"
        run: hatch run typecheck:all
