name: "Unit tests"

on:
  pull_request:
    branches:
      - "main"
      - "*.latest"
  workflow_call:
    inputs:
      branch:
        description: "The branch to run unit tests on"
        type: string
        default: "main"
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to run unit tests on"
        type: string
        default: "main"

permissions: read-all

# will cancel previous workflows triggered by the same event and for the same ref for PRs or same SHA otherwise
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ contains(github.event_name, 'workflow_') && inputs.branch || contains(github.event_name, 'pull_request') && github.event.pull_request.head.ref }}
  cancel-in-progress: true

env:
  NOTIFICATION_PREFIX: "[Unit tests]"

jobs:
  unit:
    name: "Unit tests"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest]
    steps:
      - name: "[DEBUG] Inputs"
        run: |
          echo branch              : ${{ inputs.branch }}
          echo NOTIFICATION_PREFIX : ${{ env.NOTIFICATION_PREFIX }}

      - name: "Check out `${{ contains(github.event_name, 'workflow_') && inputs.branch || contains(github.event_name, 'pull_request') && github.event.pull_request.head.ref }}`"
        uses: actions/checkout@v4
        with:
          ref: ${{ contains(github.event_name, 'workflow_') && inputs.branch || contains(github.event_name, 'pull_request') && github.event.pull_request.head.ref || github.sha }}
          persist-credentials: false

      - name: "Setup `hatch`"
        uses: ./.github/actions/setup-hatch
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Run unit tests"
        run: hatch run unit-tests:all
        shell: bash
