name: "Merge GitHub branch"
description: "Merge one branch into another on GitHub"

inputs:
  source-branch:
    description: "The source branch to be merged"
    required: true
  target-branch:
    description: "The target branch to receive the merge"
    required: true
  message:
    description: "Commit message for the merge"
    required: true
  delete-source-branch:
    description: "Will delete the source branch after merging"
    default: "true"

outputs:
  sha:
    description: "The commit SHA for the merge"
    value: ${{ steps.merge-sha.outputs.sha }}

runs:
  using: composite
  steps:
    # TODO: are we comfortable passing our bot token to this third party action?
    - name: "Merge `${{ inputs.source-branch }}` into `${{ inputs.target-branch }}`"
      uses: everlytic/branch-merge@1.1.5
      with:
        source_ref: ${{ inputs.source-branch }}
        target_branch: ${{ inputs.target-branch }}
        commit_message_template: "[automated] ${{ inputs.message }}"
        github_token: ${{ secrets.FISHTOWN_BOT_PAT }}

    - name: "Checkout `${{ inputs.branch }}`"
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.target-branch }}

    # TODO: see if everlytic/branch-merge has outputs that have this information
    - name: "Get commit SHA for the merge"
      id: merge-sha
      shell: bash
      run: |
        git pull
        echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    # TODO: see if everlytic/branch-merge has options to do this
    - name: "Delete `${{ inputs.source-branch }}`"
      if: ${{ fromJSON(inputs.delete-source-branch) }}
      shell: bash
      run: git push origin -d ${{ inputs.source-branch }}

    - name: "[INFO] Merged changes"
      shell: bash
      run: |
        title="Merged changes"
        message="${{ inputs.source-branch }} was merged into ${{ inputs.target-branch }} with sha ${{ steps.merge-sha.outputs.sha }}"
        echo "::notice title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
