name: "Audit GitHub team"
description: "Get metadata about a GitHub team, such as a list of team members"

inputs:
  organization:
    description: "The GitHub organization that owns the team"
    required: true
  team:
    description: "The name of the team"
    required: true

outputs:
  members:
    description: "A space delimited list of team members"
    value: ${{ steps.members.outputs.membership }}

runs:
  using: composite
  steps:
    - name: "Set: output file name"
      id: output-file
      run: echo "name=output_$GITHUB_RUN_ID.json" >> $GITHUB_OUTPUT

    - name: "Get team membership for `${{ inputs.organization }}/${{ inputs.team }}`"
      run: |
        url = orgs/${{ inputs.organization }}/teams/${{ inputs.team }}/members
        header = Accept: application/vnd.github+json
        gh api -H "$header" $url > ${{ steps.output-file.outputs.name }}

    - name: "Parse team membership"
      id: members
      shell:
      run: |
        team_list=$(jq -r '.[].login' ${{ steps.output-file.outputs.name }})
        team_list_single=$(echo $team_list | tr '\n' ' ')
        echo "membership=$team_list_single" >> $GITHUB_OUTPUT

    - name: "[DEBUG] Parse team membership"
      shell: bash
      run: |
        echo organization : ${{ inputs.organization }}
        echo team         : ${{ inputs.team }}
        echo members      : ${{ steps.members.outputs.membership }}

    - name: "Delete the output file"
      run: rm ${{ steps.output-file.outputs.name }}
